services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres
    volumes:
      - postgres:/val/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    
  redis:
    image: redis:8.4-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command: ['redis server', '--requirepass', '${REDIS_PASSWORD}']

volumes:
  postgres: 
  redis_data:
    driver: local